export const contentBodyClass = "prose md:max-w-screen-xl md:mx-auto my-20 p-4 pt-2";
export const createBtnContainerClass = "flex justify-end fixed bottom-0 inset-x-0 p-4 bg-base-100 z-10";
export const formClass = "bg-base-300 px-4 pt-4 pb-2 rounded-lg";
export const inputClass = "input input-bordered w-full";
export const selectClass = "select select-bordered w-full";
export const respTRClass = "relative block px-4 py-2 md:p-0 md:table-row min-h-16 md:min-h-0 text-pretty";
export const TDClass = "border-b-0 whitespace-normal leading-5";
export const respTDClass = `${TDClass} inline md:table-cell p-0 md:p-4 bg-transparent empty:hidden md:empty:table-cell before:content-[attr(data-label)] md:before:hidden`;
export const respMidTDClass = `${respTDClass} border-r border-base-content/20 md:border-none pr-2 mr-2`;
